<?php

namespace AppBundle\Repository;

/**
 * WallpaperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WallpaperRepository extends \Doctrine\ORM\EntityRepository
{
}
