# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.command.wallpaper_setup:
        class: AppBundle\Command\SetupWallpapersCommand
        arguments:
            - "%kernel.root_dir%"
            - "@doctrine.orm.default_entity_manager"
        tags:
            - { name: console.command }


    app.service.local_filesystem_file_mover:
        class: AppBundle\Service\LocalFilesystemFileMover
        arguments:
            - "@filesystem"

    app.service.wallpaper_file_path_helper:
        class: AppBundle\Service\WallpaperFilePathHelper
        arguments:
            - "%wallpaper_file_path%"

    app.service.local_filesystem_file_deleter:
        class: AppBundle\Service\LocalFilesystemFileDeleter
        arguments:
            - "@filesystem"
            - "%wallpaper_file_path%"

    app.doctrine_event_listener.wallpaper_listener:
        class: AppBundle\Event\Listener\WallpaperListener
        arguments:
            - "@app.service.local_filesystem_file_mover"
            - "@app.service.wallpaper_file_path_helper"
            - "@app.service.local_filesystem_file_deleter"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }


    app.form.type.custom_file_type:
        class: AppBundle\Form\Type\CustomFileType
        arguments:
            - "@logger"
        tags:
            - { name: form.type, alias: custom_file_type }